CREATE OR REPLACE VIEW SCM.ONT.V_SUPPLY_RISK AS
SELECT
    SC.ANCESTOR                                           AS ROOT_SUPPLIER_ID,
    S_ROOT.SUPPLIER_NAME                                  AS ROOT_SUPPLIER_NAME,
    SC.TIER_DEPTH + 1                                     AS TIER_DEPTH, -- 1-indexed for business users
    SC.PATH_CONFIDENCE,
    P.PART_ID,
    P.PART_NAME,
    PL.PLANT_ID,
    PL.PLANT_NAME,
    O.ORDER_ID,
    O.CUSTOMER_ID,
    DATEDIFF('day', CURRENT_DATE(), O.PROMISED_DATE)     AS DAYS_TO_IMPACT,
    SH.SHIPMENT_ID,
    SH.STATUS                                             AS SHIPMENT_STATUS,
    IFF(SH.ACTUAL_DATE IS NULL OR SH.ACTUAL_DATE <= SH.EXPECTED_DATE, TRUE, FALSE) AS IS_ON_TIME,
    DATEDIFF('day', SH.EXPECTED_DATE, COALESCE(SH.ACTUAL_DATE, CURRENT_DATE())) AS DAYS_DELAYED,
    C.CONTRACT_ID,
    COALESCE(C.PENALTY_PCT, 0)                             AS PENALTY_PCT,
    COALESCE(C.SLA_DAYS, 1)                                AS SLA_DAYS,

    ROUND(
        (CASE 
            WHEN SC.TIER_DEPTH = 0 THEN 1.0
            WHEN SC.TIER_DEPTH = 1 THEN 1.3
            ELSE 1.6
         END) 
        * LEAST(GREATEST(DATEDIFF('day', SH.EXPECTED_DATE, COALESCE(SH.ACTUAL_DATE, CURRENT_DATE())), 0) / NULLIF(COALESCE(C.SLA_DAYS, 1), 0), 2.0)
        * (1 + (COALESCE(C.PENALTY_PCT, 0) / 100.0))
        * SC.PATH_CONFIDENCE 
        * 50.0, 
    2) AS ROW_RISK_SCORE

FROM SCM.ONT.SUPPLIER_CLOSURE SC
JOIN SCM.RAW.SUPPLIER S_ROOT  ON S_ROOT.SUPPLIER_ID = SC.ANCESTOR
JOIN SCM.RAW.PART P           ON P.SUPPLIER_ID = SC.DESCENDANT
JOIN SCM.RAW.PLANT_PART_BOM B ON B.PART_ID = P.PART_ID
JOIN SCM.RAW.PLANT PL         ON PL.PLANT_ID = B.PLANT_ID
JOIN SCM.RAW.ORDER_ O         ON O.PLANT_ID = PL.PLANT_ID
LEFT JOIN SCM.RAW.SHIPMENT SH ON SH.PART_ID = P.PART_ID AND SH.LEG_TYPE = 'INBOUND'
LEFT JOIN SCM.RAW.CONTRACT C  ON C.SUPPLIER_ID = SC.DESCENDANT
WHERE SH.STATUS = 'DELAYED';

CREATE OR REPLACE VIEW SCM.ONT.SV_SUPPLY_CHAIN AS
SELECT 
    ROOT_SUPPLIER_ID,
    ROOT_SUPPLIER_NAME,
    TIER_DEPTH,
    CONTRACT_ID,
    PENALTY_PCT,
    ROW_RISK_SCORE,
    ORDER_ID,
    PART_NAME,
    PLANT_NAME,
    DAYS_TO_IMPACT,
    SHIPMENT_ID,
    SHIPMENT_STATUS,
    IS_ON_TIME
FROM SCM.ONT.V_SUPPLY_RISK;
