-- 1. Create search-optimized contract view
CREATE OR REPLACE VIEW SCM.ONT.V_CONTRACT_SEARCH AS
SELECT 
    C.CONTRACT_ID,
    C.SUPPLIER_ID,
    S.SUPPLIER_NAME,
    C.PENALTY_CLAUSE_TEXT,
    C.PENALTY_PCT,
    C.SLA_DAYS,
    CONCAT('Supplier: ', S.SUPPLIER_NAME, ' | SLA: ', C.SLA_DAYS, ' days | Penalty: ', C.PENALTY_PCT, '% | Clause: ', C.PENALTY_CLAUSE_TEXT) AS SEARCH_DOCUMENT
FROM SCM.RAW.CONTRACT C
JOIN SCM.RAW.SUPPLIER S ON S.SUPPLIER_ID = C.SUPPLIER_ID;

-- 2. Create Cortex Search Index on Contract Terms
CREATE OR REPLACE CORTEX SEARCH SERVICE SCM.ONT.CONTRACT_SEARCH_INDEX
ON SEARCH_DOCUMENT
ATTRIBUTES SUPPLIER_ID, PENALTY_PCT, SLA_DAYS
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 hour'
AS (
    SELECT 
        CONTRACT_ID,
        SUPPLIER_ID,
        SUPPLIER_NAME,
        PENALTY_CLAUSE_TEXT,
        PENALTY_PCT,
        SLA_DAYS,
        SEARCH_DOCUMENT
    FROM SCM.ONT.V_CONTRACT_SEARCH
);
