-- 1. Raw Baseline Schema Setup
CREATE TABLE IF NOT EXISTS SCM.RAW.SUPPLIER (
    SUPPLIER_ID         VARCHAR(36) PRIMARY KEY,
    SUPPLIER_NAME       VARCHAR(200),
    PARENT_SUPPLIER_ID  VARCHAR(36),
    REGION              VARCHAR(100),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    SOURCE_TYPE         VARCHAR(30),
    SOURCE_LAST_UPDATED DATE,
    CONFIDENCE_SCORE    NUMBER(3,2)
);

CREATE TABLE IF NOT EXISTS SCM.RAW.PART (
    PART_ID           VARCHAR(36) PRIMARY KEY,
    PART_NAME         VARCHAR(200),
    SUPPLIER_ID       VARCHAR(36),
    UNIT_COST         NUMBER(12,2)
);

CREATE TABLE IF NOT EXISTS SCM.RAW.PLANT (
    PLANT_ID          VARCHAR(36) PRIMARY KEY,
    PLANT_NAME        VARCHAR(200),
    REGION            VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS SCM.RAW.PLANT_PART_BOM (
    PLANT_ID          VARCHAR(36),
    PART_ID           VARCHAR(36),
    QTY_PER_UNIT      NUMBER(10,2),
    PRIMARY KEY (PLANT_ID, PART_ID)
);

CREATE TABLE IF NOT EXISTS SCM.RAW.ORDER_ (
    ORDER_ID          VARCHAR(36) PRIMARY KEY,
    CUSTOMER_ID       VARCHAR(36),
    PLANT_ID          VARCHAR(36),
    ORDER_DATE        DATE,
    PROMISED_DATE     DATE,
    QTY_ORDERED       NUMBER(12,2),
    QTY_FULFILLED     NUMBER(12,2) DEFAULT 0,
    STATUS            VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS SCM.RAW.SHIPMENT (
    SHIPMENT_ID       VARCHAR(36) PRIMARY KEY,
    ORIGIN_ID         VARCHAR(36),
    DESTINATION_ID    VARCHAR(36),
    LEG_TYPE          VARCHAR(20),
    PART_ID           VARCHAR(36),
    ORDER_ID          VARCHAR(36),
    ROUTE_ID          VARCHAR(36),
    QTY_SHIPPED       NUMBER(12,2),
    DISPATCH_DATE     DATE,
    EXPECTED_DATE     DATE,
    ACTUAL_DATE       DATE,
    STATUS            VARCHAR(20)
);

-- 2. Confidence & Multi-Tier Closure Table
CREATE OR REPLACE VIEW SCM.ONT.V_SUPPLIER_CONFIDENCE AS
SELECT
    SUPPLIER_ID,
    PARENT_SUPPLIER_ID,
    SOURCE_TYPE,
    DATEDIFF('day', COALESCE(SOURCE_LAST_UPDATED, CURRENT_DATE()), CURRENT_DATE()) AS DAYS_STALE,
    CASE SOURCE_TYPE
        WHEN 'TRADE_DATA_VERIFIED' THEN 0.90
        WHEN 'THIRD_PARTY_INTEL'   THEN 0.80
        WHEN 'SELF_DISCLOSED'      THEN 0.60
        ELSE 0.00
    END
    * CASE
        WHEN DATEDIFF('day', COALESCE(SOURCE_LAST_UPDATED, CURRENT_DATE()), CURRENT_DATE()) > 540 THEN 0.5
        WHEN DATEDIFF('day', COALESCE(SOURCE_LAST_UPDATED, CURRENT_DATE()), CURRENT_DATE()) > 180 THEN 0.8
        ELSE 1.0
      END AS CONFIDENCE_SCORE
FROM SCM.RAW.SUPPLIER;

CREATE OR REPLACE TABLE SCM.ONT.SUPPLIER_CLOSURE (
    DESCENDANT VARCHAR(36),
    ANCESTOR VARCHAR(36),
    TIER_DEPTH NUMBER,
    PATH_CONFIDENCE FLOAT
);

INSERT INTO SCM.ONT.SUPPLIER_CLOSURE (DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE)
WITH RECURSIVE CHAIN (DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE) AS (
    SELECT
        SUPPLIER_ID AS DESCENDANT,
        SUPPLIER_ID AS ANCESTOR,
        0 AS TIER_DEPTH,
        1.0::FLOAT AS PATH_CONFIDENCE
    FROM SCM.RAW.SUPPLIER

    UNION ALL

    SELECT
        C.DESCENDANT,
        S.PARENT_SUPPLIER_ID AS ANCESTOR,
        C.TIER_DEPTH + 1 AS TIER_DEPTH,
        (C.PATH_CONFIDENCE * COALESCE(VC.CONFIDENCE_SCORE, 0.0))::FLOAT AS PATH_CONFIDENCE
    FROM CHAIN C
    JOIN SCM.RAW.SUPPLIER S ON S.SUPPLIER_ID = C.ANCESTOR
    LEFT JOIN SCM.ONT.V_SUPPLIER_CONFIDENCE VC ON VC.SUPPLIER_ID = S.SUPPLIER_ID
    WHERE S.PARENT_SUPPLIER_ID IS NOT NULL
)
SELECT DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE FROM CHAIN;

-- 3. Dynamic Cascade Risk View
CREATE OR REPLACE VIEW SCM.ONT.V_SUPPLY_RISK AS
SELECT
    SC.ANCESTOR                                           AS ROOT_SUPPLIER_ID,
    S_ROOT.SUPPLIER_NAME                                  AS ROOT_SUPPLIER_NAME,
    SC.TIER_DEPTH,
    SC.PATH_CONFIDENCE,
    P.PART_ID,
    P.PART_NAME,
    PL.PLANT_ID,
    PL.PLANT_NAME,
    O.ORDER_ID,
    O.CUSTOMER_ID,
    DATEDIFF('day', CURRENT_DATE(), O.PROMISED_DATE)     AS DAYS_TO_IMPACT,
    SH.SHIPMENT_ID,
    SH.STATUS                                             AS SHIPMENT_STATUS,
    IFF(SH.ACTUAL_DATE IS NULL OR SH.ACTUAL_DATE <= SH.EXPECTED_DATE, TRUE, FALSE) AS IS_ON_TIME,
    DATEDIFF('day', SH.EXPECTED_DATE, COALESCE(SH.ACTUAL_DATE, CURRENT_DATE())) AS DAYS_DELAYED,
    C.CONTRACT_ID,
    COALESCE(C.PENALTY_PCT, 0)                             AS PENALTY_PCT,
    COALESCE(C.SLA_DAYS, 1)                                AS SLA_DAYS,

    ROUND(
        (CASE 
            WHEN SC.TIER_DEPTH = 1 THEN 1.0
            WHEN SC.TIER_DEPTH = 2 THEN 1.3
            ELSE 1.6
         END) 
        * LEAST(GREATEST(DATEDIFF('day', SH.EXPECTED_DATE, COALESCE(SH.ACTUAL_DATE, CURRENT_DATE())), 0) / NULLIF(COALESCE(C.SLA_DAYS, 1), 0), 2.0)
        * (1 + (COALESCE(C.PENALTY_PCT, 0) / 100.0))
        * SC.PATH_CONFIDENCE 
        * 50.0, 
    2) AS ROW_RISK_SCORE

FROM SCM.ONT.SUPPLIER_CLOSURE SC
JOIN SCM.RAW.SUPPLIER S_ROOT  ON S_ROOT.SUPPLIER_ID = SC.ANCESTOR
JOIN SCM.RAW.PART P           ON P.SUPPLIER_ID = SC.DESCENDANT
JOIN SCM.RAW.PLANT_PART_BOM B ON B.PART_ID = P.PART_ID
JOIN SCM.RAW.PLANT PL         ON PL.PLANT_ID = B.PLANT_ID
JOIN SCM.RAW.ORDER_ O         ON O.PLANT_ID = PL.PLANT_ID
LEFT JOIN SCM.RAW.SHIPMENT SH ON SH.PART_ID = P.PART_ID AND SH.LEG_TYPE = 'INBOUND'
LEFT JOIN SCM.RAW.CONTRACT C  ON C.SUPPLIER_ID = SC.ANCESTOR
WHERE SH.STATUS = 'DELAYED';

-- 4. Re-create SV_SUPPLY_CHAIN Analytical View
CREATE OR REPLACE VIEW SCM.ONT.SV_SUPPLY_CHAIN AS
SELECT 
    ROOT_SUPPLIER_ID,
    ROOT_SUPPLIER_NAME,
    TIER_DEPTH,
    CONTRACT_ID,
    PENALTY_PCT,
    ROW_RISK_SCORE,
    ORDER_ID,
    PART_NAME,
    PLANT_NAME,
    DAYS_TO_IMPACT,
    SHIPMENT_ID,
    SHIPMENT_STATUS,
    IS_ON_TIME
FROM SCM.ONT.V_SUPPLY_RISK;

-- 5. Seed Risk Alerts
INSERT INTO SCM.ONT.DETECTED_RISK_ALERTS (
    ALERT_ID,
    SUPPLIER_ID,
    SEVERITY,
    RISK_TYPE,
    DESCRIPTION,
    DETECTED_AT
)
SELECT 
    UUID_STRING() AS ALERT_ID,
    ROOT_SUPPLIER_ID AS SUPPLIER_ID,
    CASE 
        WHEN ROW_RISK_SCORE >= 50 THEN 'CRITICAL'
        WHEN ROW_RISK_SCORE >= 25 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS SEVERITY,
    'SUPPLY_CASCADE' AS RISK_TYPE,
    CONCAT('Tier-', TIER_DEPTH, ' risk propagation: Supplier ', ROOT_SUPPLIER_NAME, ' impacts Order ', ORDER_ID, ' on Part ', PART_NAME, ' at ', PLANT_NAME, ' in ', DAYS_TO_IMPACT, ' days.') AS DESCRIPTION,
    CURRENT_TIMESTAMP() AS DETECTED_AT
FROM SCM.ONT.SV_SUPPLY_CHAIN
WHERE ROW_RISK_SCORE > 15.0;
