-- 1. Re-populate SUPPLIER_CLOSURE with multi-hop recursive traversal
TRUNCATE TABLE SCM.ONT.SUPPLIER_CLOSURE;

INSERT INTO SCM.ONT.SUPPLIER_CLOSURE (DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE)
WITH RECURSIVE CHAIN (DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE) AS (
    -- Base Case: Self-reference at Depth 0 (Tier-1 to itself)
    SELECT
        SUPPLIER_ID AS DESCENDANT,
        SUPPLIER_ID AS ANCESTOR,
        0 AS TIER_DEPTH,
        1.0::FLOAT AS PATH_CONFIDENCE
    FROM SCM.RAW.SUPPLIER

    UNION ALL

    -- Recursive Case: Walk DOWN the tree (Parent -> Child) or UP (Child -> Parent)
    -- DESCENDANT remains the Tier-1 supplier tied to PART; ANCESTOR becomes the sub-tier root
    SELECT
        C.DESCENDANT,
        S.SUPPLIER_ID AS ANCESTOR,
        C.TIER_DEPTH + 1 AS TIER_DEPTH,
        (C.PATH_CONFIDENCE * COALESCE(VC.CONFIDENCE_SCORE, 0.80))::FLOAT AS PATH_CONFIDENCE
    FROM CHAIN C
    JOIN SCM.RAW.SUPPLIER S ON S.PARENT_SUPPLIER_ID = C.ANCESTOR
    LEFT JOIN SCM.ONT.V_SUPPLIER_CONFIDENCE VC ON VC.SUPPLIER_ID = S.SUPPLIER_ID
)
SELECT DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE FROM CHAIN;

-- 2. Re-create V_SUPPLY_RISK to accurately present root causes and TIER_DEPTH
CREATE OR REPLACE VIEW SCM.ONT.V_SUPPLY_RISK AS
SELECT
    SC.ANCESTOR                                           AS ROOT_SUPPLIER_ID,
    S_ROOT.SUPPLIER_NAME                                  AS ROOT_SUPPLIER_NAME,
    SC.TIER_DEPTH,
    SC.PATH_CONFIDENCE,
    P.PART_ID,
    P.PART_NAME,
    PL.PLANT_ID,
    PL.PLANT_NAME,
    O.ORDER_ID,
    O.CUSTOMER_ID,
    DATEDIFF('day', CURRENT_DATE(), O.PROMISED_DATE)     AS DAYS_TO_IMPACT,
    SH.SHIPMENT_ID,
    SH.STATUS                                             AS SHIPMENT_STATUS,
    IFF(SH.ACTUAL_DATE IS NULL OR SH.ACTUAL_DATE <= SH.EXPECTED_DATE, TRUE, FALSE) AS IS_ON_TIME,
    DATEDIFF('day', SH.EXPECTED_DATE, COALESCE(SH.ACTUAL_DATE, CURRENT_DATE())) AS DAYS_DELAYED,
    C.CONTRACT_ID,
    COALESCE(C.PENALTY_PCT, 0)                             AS PENALTY_PCT,
    COALESCE(C.SLA_DAYS, 1)                                AS SLA_DAYS,

    ROUND(
        (CASE 
            WHEN SC.TIER_DEPTH = 0 THEN 1.0
            WHEN SC.TIER_DEPTH = 1 THEN 1.3
            ELSE 1.6
         END) 
        * LEAST(GREATEST(DATEDIFF('day', SH.EXPECTED_DATE, COALESCE(SH.ACTUAL_DATE, CURRENT_DATE())), 0) / NULLIF(COALESCE(C.SLA_DAYS, 1), 0), 2.0)
        * (1 + (COALESCE(C.PENALTY_PCT, 0) / 100.0))
        * SC.PATH_CONFIDENCE 
        * 50.0, 
    2) AS ROW_RISK_SCORE

FROM SCM.ONT.SUPPLIER_CLOSURE SC
JOIN SCM.RAW.SUPPLIER S_ROOT  ON S_ROOT.SUPPLIER_ID = SC.ANCESTOR
JOIN SCM.RAW.PART P           ON P.SUPPLIER_ID = SC.DESCENDANT
JOIN SCM.RAW.PLANT_PART_BOM B ON B.PART_ID = P.PART_ID
JOIN SCM.RAW.PLANT PL         ON PL.PLANT_ID = B.PLANT_ID
JOIN SCM.RAW.ORDER_ O         ON O.PLANT_ID = PL.PLANT_ID
LEFT JOIN SCM.RAW.SHIPMENT SH ON SH.PART_ID = P.PART_ID AND SH.LEG_TYPE = 'INBOUND'
LEFT JOIN SCM.RAW.CONTRACT C  ON C.SUPPLIER_ID = SC.DESCENDANT
WHERE SH.STATUS = 'DELAYED';

-- 3. Re-create SV_SUPPLY_CHAIN
CREATE OR REPLACE VIEW SCM.ONT.SV_SUPPLY_CHAIN AS
SELECT 
    ROOT_SUPPLIER_ID,
    ROOT_SUPPLIER_NAME,
    TIER_DEPTH,
    CONTRACT_ID,
    PENALTY_PCT,
    ROW_RISK_SCORE,
    ORDER_ID,
    PART_NAME,
    PLANT_NAME,
    DAYS_TO_IMPACT,
    SHIPMENT_ID,
    SHIPMENT_STATUS,
    IS_ON_TIME
FROM SCM.ONT.V_SUPPLY_RISK;
