-- Clear old baseline data
TRUNCATE TABLE IF EXISTS SCM.RAW.SHIPMENT;
TRUNCATE TABLE IF EXISTS SCM.RAW.ORDER_;
TRUNCATE TABLE IF EXISTS SCM.RAW.PLANT_PART_BOM;
TRUNCATE TABLE IF EXISTS SCM.RAW.PLANT;
TRUNCATE TABLE IF EXISTS SCM.RAW.PART;
TRUNCATE TABLE IF EXISTS SCM.RAW.CONTRACT;
TRUNCATE TABLE IF EXISTS SCM.RAW.SUPPLIER;
TRUNCATE TABLE IF EXISTS SCM.ONT.SUPPLIER_CLOSURE;
TRUNCATE TABLE IF EXISTS SCM.ONT.DETECTED_RISK_ALERTS;

-- 1. Insert Suppliers (N-tier network)
INSERT INTO SCM.RAW.SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, PARENT_SUPPLIER_ID, REGION, SOURCE_TYPE, SOURCE_LAST_UPDATED) VALUES
('SUP-001', 'Apex Components', NULL, 'North America', 'TRADE_DATA_VERIFIED', CURRENT_DATE()),
('SUP-002', 'Global Tech Parts', NULL, 'Asia-Pacific', 'TRADE_DATA_VERIFIED', CURRENT_DATE()),
('SUP-101', 'Sub-Tier Silicon Co', 'SUP-001', 'Asia-Pacific', 'TRADE_DATA_VERIFIED', CURRENT_DATE() - 30),
('SUP-102', 'MicroLogix Chips', 'SUP-001', 'Europe', 'SELF_DISCLOSED', CURRENT_DATE() - 200),
('SUP-201', 'Raw Quartz Mining', 'SUP-101', 'South America', 'THIRD_PARTY_INTEL', CURRENT_DATE() - 600);

-- 2. Insert Contracts (Tier 1)
INSERT INTO SCM.RAW.CONTRACT (CONTRACT_ID, SUPPLIER_ID, PENALTY_CLAUSE_TEXT, PENALTY_PCT, SLA_DAYS) VALUES
('CT-001', 'SUP-001', 'Late delivery beyond 5 days incurs a 10% penalty on total order value.', 10.00, 5),
('CT-002', 'SUP-002', 'Late delivery beyond 3 days incurs a 5% penalty.', 5.00, 3);

-- 3. Insert Parts
INSERT INTO SCM.RAW.PART (PART_ID, PART_NAME, SUPPLIER_ID, UNIT_COST) VALUES
('PRT-A1', 'Microcontroller Unit A1', 'SUP-001', 45.00),
('PRT-B2', 'Power Converter Module', 'SUP-002', 120.00);

-- 4. Insert Manufacturing Plants
INSERT INTO SCM.RAW.PLANT (PLANT_ID, PLANT_NAME, REGION) VALUES
('PLT-01', 'Austin Assembly Plant', 'Texas, USA'),
('PLT-02', 'Munich Tech Works', 'Germany');

-- 5. Insert Plant BOM
INSERT INTO SCM.RAW.PLANT_PART_BOM (PLANT_ID, PART_ID, QTY_PER_UNIT) VALUES
('PLT-01', 'PRT-A1', 2.0),
('PLT-02', 'PRT-B2', 1.0);

-- 6. Insert Orders
INSERT INTO SCM.RAW.ORDER_ (ORDER_ID, CUSTOMER_ID, PLANT_ID, ORDER_DATE, PROMISED_DATE, QTY_ORDERED, QTY_FULFILLED, STATUS) VALUES
('ORD-9001', 'CUST-801', 'PLT-01', CURRENT_DATE() - 10, CURRENT_DATE() + 5, 500, 0, 'AT_RISK'),
('ORD-9002', 'CUST-802', 'PLT-02', CURRENT_DATE() - 5, CURRENT_DATE() + 12, 200, 0, 'OPEN');

-- 7. Insert Delayed Inbound Shipments
INSERT INTO SCM.RAW.SHIPMENT (SHIPMENT_ID, ORIGIN_ID, DESTINATION_ID, LEG_TYPE, PART_ID, ORDER_ID, ROUTE_ID, QTY_SHIPPED, DISPATCH_DATE, EXPECTED_DATE, ACTUAL_DATE, STATUS) VALUES
('SHP-501', 'SUP-001', 'PLT-01', 'INBOUND', 'PRT-A1', 'ORD-9001', 'RT-10', 1000, CURRENT_DATE() - 8, CURRENT_DATE() - 2, NULL, 'DELAYED'),
('SHP-502', 'SUP-002', 'PLT-02', 'INBOUND', 'PRT-B2', 'ORD-9002', 'RT-12', 200, CURRENT_DATE() - 3, CURRENT_DATE() + 2, NULL, 'DELAYED');

-- 8. Populate Supplier Closure Table
INSERT INTO SCM.ONT.SUPPLIER_CLOSURE (DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE)
WITH RECURSIVE CHAIN (DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE) AS (
    SELECT
        SUPPLIER_ID AS DESCENDANT,
        SUPPLIER_ID AS ANCESTOR,
        0 AS TIER_DEPTH,
        1.0::FLOAT AS PATH_CONFIDENCE
    FROM SCM.RAW.SUPPLIER

    UNION ALL

    SELECT
        C.DESCENDANT,
        S.PARENT_SUPPLIER_ID AS ANCESTOR,
        C.TIER_DEPTH + 1 AS TIER_DEPTH,
        (C.PATH_CONFIDENCE * COALESCE(VC.CONFIDENCE_SCORE, 0.0))::FLOAT AS PATH_CONFIDENCE
    FROM CHAIN C
    JOIN SCM.RAW.SUPPLIER S ON S.SUPPLIER_ID = C.ANCESTOR
    LEFT JOIN SCM.ONT.V_SUPPLIER_CONFIDENCE VC ON VC.SUPPLIER_ID = S.SUPPLIER_ID
    WHERE S.PARENT_SUPPLIER_ID IS NOT NULL
)
SELECT DESCENDANT, ANCESTOR, TIER_DEPTH, PATH_CONFIDENCE FROM CHAIN;

-- 9. Seed Detected Risk Alerts
INSERT INTO SCM.ONT.DETECTED_RISK_ALERTS (
    ALERT_ID,
    SUPPLIER_ID,
    SEVERITY,
    RISK_TYPE,
    DESCRIPTION,
    DETECTED_AT
)
SELECT 
    UUID_STRING() AS ALERT_ID,
    ROOT_SUPPLIER_ID AS SUPPLIER_ID,
    CASE 
        WHEN ROW_RISK_SCORE >= 50 THEN 'CRITICAL'
        WHEN ROW_RISK_SCORE >= 25 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS SEVERITY,
    'SUPPLY_CASCADE' AS RISK_TYPE,
    CONCAT('Tier-', TIER_DEPTH, ' risk propagation: Supplier ', ROOT_SUPPLIER_NAME, ' impacts Order ', ORDER_ID, ' on Part ', PART_NAME, ' at ', PLANT_NAME, ' in ', DAYS_TO_IMPACT, ' days.') AS DESCRIPTION,
    CURRENT_TIMESTAMP() AS DETECTED_AT
FROM SCM.ONT.SV_SUPPLY_CHAIN
WHERE ROW_RISK_SCORE > 10.0;
