USE DATABASE SCM;
USE SCHEMA ONT;

-- 1. Create Route Table if not exists
CREATE TABLE IF NOT EXISTS SCM.RAW.ROUTE (
    ROUTE_ID VARCHAR(50) PRIMARY KEY,
    ORIGIN_SUPPLIER_ID VARCHAR(50),
    DESTINATION_PLANT_ID VARCHAR(50),
    TRANSIT_MODE VARCHAR(50),
    AVG_TRANSIT_DAYS NUMBER(5,1),
    RISK_FACTOR NUMBER(3,2)
);

-- Seed Routes using MERGE for safe rerun
MERGE INTO SCM.RAW.ROUTE AS target
USING (
    SELECT 'RT-001' AS ROUTE_ID, 'SUP-001' AS ORIGIN_SUPPLIER_ID, 'PLT-01' AS DESTINATION_PLANT_ID, 'ROAD_EXPRESS' AS TRANSIT_MODE, 2.5 AS AVG_TRANSIT_DAYS, 0.15 AS RISK_FACTOR UNION ALL
    SELECT 'RT-002', 'SUP-002', 'PLT-02', 'AIR_FREIGHT', 4.0, 0.25 UNION ALL
    SELECT 'RT-003', 'SUP-005', 'PLT-01', 'RAIL_CARGO', 6.0, 0.10 UNION ALL
    SELECT 'RT-004', 'SUP-008', 'PLT-03', 'SEA_FREIGHT', 14.0, 0.35
) AS source
ON target.ROUTE_ID = source.ROUTE_ID
WHEN NOT MATCHED THEN
    INSERT (ROUTE_ID, ORIGIN_SUPPLIER_ID, DESTINATION_PLANT_ID, TRANSIT_MODE, AVG_TRANSIT_DAYS, RISK_FACTOR)
    VALUES (source.ROUTE_ID, source.ORIGIN_SUPPLIER_ID, source.DESTINATION_PLANT_ID, source.TRANSIT_MODE, source.AVG_TRANSIT_DAYS, source.RISK_FACTOR);

-- 2. Update SUPPLIER metadata with Source Types and Dates for Confidence Scoring
ALTER TABLE SCM.RAW.SUPPLIER ADD COLUMN IF NOT EXISTS SOURCE_TYPE VARCHAR(50);
ALTER TABLE SCM.RAW.SUPPLIER ADD COLUMN IF NOT EXISTS LAST_UPDATED_DATE DATE;

UPDATE SCM.RAW.SUPPLIER SET 
    SOURCE_TYPE = CASE 
        WHEN SUPPLIER_ID IN ('SUP-001','SUP-002','SUP-003','SUP-005','SUP-006','SUP-008','SUP-101','SUP-103','SUP-105','SUP-202','SUP-203') THEN 'TRADE_DATA_VERIFIED'
        WHEN SUPPLIER_ID IN ('SUP-004','SUP-007','SUP-102','SUP-104','SUP-204') THEN 'SELF_DISCLOSED'
        WHEN SUPPLIER_ID IN ('SUP-106','SUP-201') THEN 'THIRD_PARTY_INTEL'
        ELSE 'UNKNOWN'
    END,
    LAST_UPDATED_DATE = CASE 
        WHEN SUPPLIER_ID IN ('SUP-001','SUP-002','SUP-003') THEN CURRENT_DATE()
        WHEN SUPPLIER_ID IN ('SUP-104','SUP-107','SUP-205') THEN DATEADD('month', -20, CURRENT_DATE())
        ELSE DATEADD('month', -4, CURRENT_DATE())
    END;
