USE DATABASE SCM;
USE SCHEMA ONT;

-- 1. Create or Replace Base Closure Table
CREATE OR REPLACE TABLE SCM.ONT.SUPPLIER_CLOSURE (
    ANCESTOR_SUPPLIER_ID VARCHAR(50),
    ANCESTOR_SUPPLIER_NAME VARCHAR(100),
    DESCENDANT_SUPPLIER_ID VARCHAR(50),
    DESCENDANT_SUPPLIER_NAME VARCHAR(100),
    TIER_DEPTH NUMBER,
    PATH_CONFIDENCE NUMBER(5,4),
    HOP_PATH VARCHAR(500)
);

-- 2. Populate Recursive Closure Graph with Confidence Decay
INSERT INTO SCM.ONT.SUPPLIER_CLOSURE
WITH RECURSIVE SUPPLIER_CONFIDENCE AS (
    SELECT 
        SUPPLIER_ID,
        SUPPLIER_NAME,
        PARENT_SUPPLIER_ID,
        SOURCE_TYPE,
        LAST_UPDATED_DATE,
        (
            CASE 
                WHEN SOURCE_TYPE = 'TRADE_DATA_VERIFIED' THEN 0.95
                WHEN SOURCE_TYPE = 'SELF_DISCLOSED' THEN 0.75
                WHEN SOURCE_TYPE = 'THIRD_PARTY_INTEL' THEN 0.60
                ELSE 0.30
            END * 
            CASE 
                WHEN LAST_UPDATED_DATE < DATEADD('month', -12, CURRENT_DATE()) THEN 0.90 
                ELSE 1.00 
            END
        ) AS HOP_CONFIDENCE
    FROM SCM.RAW.SUPPLIER
),
CLOSURE_CTE AS (
    -- Anchor: Tier 1 Direct Relationships (Depth 1)
    SELECT 
        s.PARENT_SUPPLIER_ID AS ANCESTOR_SUPPLIER_ID,
        p.SUPPLIER_NAME AS ANCESTOR_SUPPLIER_NAME,
        s.SUPPLIER_ID AS DESCENDANT_SUPPLIER_ID,
        s.SUPPLIER_NAME AS DESCENDANT_SUPPLIER_NAME,
        1 AS TIER_DEPTH,
        s.HOP_CONFIDENCE AS PATH_CONFIDENCE,
        p.SUPPLIER_NAME || ' -> ' || s.SUPPLIER_NAME AS HOP_PATH
    FROM SUPPLIER_CONFIDENCE s
    JOIN SUPPLIER_CONFIDENCE p ON s.PARENT_SUPPLIER_ID = p.SUPPLIER_ID
    WHERE s.PARENT_SUPPLIER_ID IS NOT NULL

    UNION ALL

    -- Recursive Step: Sub-Tier Relationships (Depth N)
    SELECT 
        c.ANCESTOR_SUPPLIER_ID,
        c.ANCESTOR_SUPPLIER_NAME,
        s.SUPPLIER_ID AS DESCENDANT_SUPPLIER_ID,
        s.SUPPLIER_NAME AS DESCENDANT_SUPPLIER_NAME,
        c.TIER_DEPTH + 1 AS TIER_DEPTH,
        ROUND(c.PATH_CONFIDENCE * s.HOP_CONFIDENCE, 4) AS PATH_CONFIDENCE,
        c.HOP_PATH || ' -> ' || s.SUPPLIER_NAME AS HOP_PATH
    FROM CLOSURE_CTE c
    JOIN SUPPLIER_CONFIDENCE s ON c.DESCENDANT_SUPPLIER_ID = s.PARENT_SUPPLIER_ID
)
SELECT 
    ANCESTOR_SUPPLIER_ID,
    ANCESTOR_SUPPLIER_NAME,
    DESCENDANT_SUPPLIER_ID,
    DESCENDANT_SUPPLIER_NAME,
    TIER_DEPTH,
    PATH_CONFIDENCE,
    HOP_PATH
FROM CLOSURE_CTE;

-- 3. Re-create Ontology View Safely
CREATE OR REPLACE VIEW SCM.ONT.SV_SUPPLY_CHAIN AS
SELECT 
    c.ANCESTOR_SUPPLIER_ID AS ROOT_SUPPLIER_ID,
    c.ANCESTOR_SUPPLIER_NAME AS ROOT_SUPPLIER_NAME,
    c.DESCENDANT_SUPPLIER_ID AS DIRECT_SUPPLIER_ID,
    c.DESCENDANT_SUPPLIER_NAME AS DIRECT_SUPPLIER_NAME,
    c.TIER_DEPTH,
    c.PATH_CONFIDENCE,
    c.HOP_PATH,
    p.PART_ID,
    p.PART_NAME,
    pl.PLANT_ID,
    pl.PLANT_NAME,
    o.ORDER_ID,
    o.ORDER_DATE AS REQUIRED_DATE,
    'IN_TRANSIT' AS SHIPMENT_STATUS,
    TRUE AS IS_ON_TIME,
    ct.CONTRACT_ID,
    ct.PENALTY_PCT,
    ct.SLA_DAYS,
    ct.PENALTY_CLAUSE_TEXT,
    DATEDIFF('day', CURRENT_DATE(), o.ORDER_DATE) AS DAYS_TO_IMPACT,
    ROUND((1.0 - c.PATH_CONFIDENCE) * 50 + COALESCE(ct.PENALTY_PCT, 0), 2) AS ROW_RISK_SCORE
FROM SCM.ONT.SUPPLIER_CLOSURE c
JOIN SCM.RAW.PART p ON c.DESCENDANT_SUPPLIER_ID = p.SUPPLIER_ID
JOIN SCM.RAW.PLANT_PART_BOM bom ON p.PART_ID = bom.PART_ID
JOIN SCM.RAW.PLANT pl ON bom.PLANT_ID = pl.PLANT_ID
LEFT JOIN SCM.RAW.ORDER_ o ON pl.PLANT_ID = o.PLANT_ID
LEFT JOIN SCM.RAW.CONTRACT ct ON c.ANCESTOR_SUPPLIER_ID = ct.SUPPLIER_ID;
