USE DATABASE SCM;
USE SCHEMA ONT;

CREATE OR REPLACE TABLE SCM.ONT.DETECTED_RISK_ALERTS (
    ALERT_ID          VARCHAR(36) DEFAULT UUID_STRING(),
    DETECTED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ROOT_SUPPLIER     VARCHAR(200),
    TIER_DEPTH        NUMBER(3,0),
    PATH_CONFIDENCE   NUMBER(3,2),
    ORDER_ID          VARCHAR(36),
    DAYS_TO_IMPACT    NUMBER(5,0),
    RISK_SCORE        NUMBER(5,2),
    STATUS            VARCHAR(20) DEFAULT 'ACTIVE'
);

INSERT INTO SCM.ONT.DETECTED_RISK_ALERTS (ROOT_SUPPLIER, TIER_DEPTH, PATH_CONFIDENCE, ORDER_ID, DAYS_TO_IMPACT, RISK_SCORE)
SELECT 
    ROOT_SUPPLIER_NAME,
    TIER_DEPTH,
    PATH_CONFIDENCE,
    ORDER_ID,
    DAYS_TO_IMPACT,
    ROW_RISK_SCORE
FROM SCM.ONT.SV_SUPPLY_CHAIN
WHERE ROW_RISK_SCORE > 3.00;
