USE DATABASE SCM;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE SUPPLIER (
    SUPPLIER_ID         VARCHAR(36) PRIMARY KEY,
    SUPPLIER_NAME       VARCHAR(200),
    PARENT_SUPPLIER_ID  VARCHAR(36),
    REGION              VARCHAR(100),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    SOURCE_TYPE         VARCHAR(30),
    SOURCE_LAST_UPDATED DATE,
    CONFIDENCE_SCORE    NUMBER(3,2)
);

CREATE OR REPLACE TABLE PART (
    PART_ID           VARCHAR(36) PRIMARY KEY,
    PART_NAME         VARCHAR(200),
    SUPPLIER_ID       VARCHAR(36),
    UNIT_COST         NUMBER(12,2)
);

CREATE OR REPLACE TABLE PLANT (
    PLANT_ID          VARCHAR(36) PRIMARY KEY,
    PLANT_NAME        VARCHAR(200),
    REGION            VARCHAR(100)
);

CREATE OR REPLACE TABLE PLANT_PART_BOM (
    PLANT_ID          VARCHAR(36),
    PART_ID           VARCHAR(36),
    QTY_PER_UNIT      NUMBER(10,2),
    PRIMARY KEY (PLANT_ID, PART_ID)
);

CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID       VARCHAR(36) PRIMARY KEY,
    CUSTOMER_NAME     VARCHAR(200),
    REGION            VARCHAR(100)
);

CREATE OR REPLACE TABLE ORDER_ (
    ORDER_ID          VARCHAR(36) PRIMARY KEY,
    CUSTOMER_ID       VARCHAR(36),
    PLANT_ID          VARCHAR(36),
    ORDER_DATE        DATE,
    PROMISED_DATE     DATE,
    QTY_ORDERED       NUMBER(12,2),
    QTY_FULFILLED     NUMBER(12,2) DEFAULT 0,
    STATUS            VARCHAR(20)
);

CREATE OR REPLACE TABLE ROUTE (
    ROUTE_ID          VARCHAR(36) PRIMARY KEY,
    ROUTE_NAME        VARCHAR(200),
    MODE              VARCHAR(30)
);

CREATE OR REPLACE TABLE SHIPMENT (
    SHIPMENT_ID       VARCHAR(36) PRIMARY KEY,
    ORIGIN_ID         VARCHAR(36),
    DESTINATION_ID    VARCHAR(36),
    LEG_TYPE          VARCHAR(20),
    PART_ID           VARCHAR(36),
    ORDER_ID          VARCHAR(36),
    ROUTE_ID          VARCHAR(36),
    QTY_SHIPPED       NUMBER(12,2),
    DISPATCH_DATE     DATE,
    EXPECTED_DATE     DATE,
    ACTUAL_DATE       DATE,
    STATUS            VARCHAR(20)
);

CREATE OR REPLACE TABLE CONTRACT (
    CONTRACT_ID          VARCHAR(36) PRIMARY KEY,
    SUPPLIER_ID          VARCHAR(36),
    PENALTY_CLAUSE_TEXT  VARCHAR(2000),
    PENALTY_PCT          NUMBER(5,2),
    SLA_DAYS             INTEGER
);
