USE DATABASE SCM;
USE SCHEMA RAW;

INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, PARENT_SUPPLIER_ID, REGION, SOURCE_TYPE, SOURCE_LAST_UPDATED) VALUES
('SUP-T3-01', 'Raw Silicon Corp', NULL, 'Asia-Pacific', 'THIRD_PARTY_INTEL', CURRENT_DATE() - 200),
('SUP-T2-01', 'Silicon Micro Devices', 'SUP-T3-01', 'Asia-Pacific', 'SELF_DISCLOSED', CURRENT_DATE() - 30),
('SUP-T1-01', 'Apex Electronics', 'SUP-T2-01', 'North America', 'TRADE_DATA_VERIFIED', CURRENT_DATE());

INSERT INTO PART (PART_ID, PART_NAME, SUPPLIER_ID, UNIT_COST) VALUES
('PART-101', 'Microcontroller Chip', 'SUP-T1-01', 12.50),
('PART-201', 'Silicon Wafer', 'SUP-T2-01', 85.00);

INSERT INTO PLANT (PLANT_ID, PLANT_NAME, REGION) VALUES ('PLANT-01', 'Austin Assembly', 'North America');

INSERT INTO PLANT_PART_BOM (PLANT_ID, PART_ID, QTY_PER_UNIT) VALUES 
('PLANT-01', 'PART-101', 2),
('PLANT-01', 'PART-201', 1);

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, REGION) VALUES ('CUST-100', 'TechCorp', 'North America');

INSERT INTO ORDER_ (ORDER_ID, CUSTOMER_ID, PLANT_ID, ORDER_DATE, PROMISED_DATE, QTY_ORDERED, STATUS) VALUES
('ORD-5501', 'CUST-100', 'PLANT-01', CURRENT_DATE() - 10, CURRENT_DATE() + 5, 1000, 'AT_RISK'),
('ORD-5502', 'CUST-100', 'PLANT-01', CURRENT_DATE() - 5, CURRENT_DATE() + 12, 500, 'AT_RISK');

INSERT INTO CONTRACT (CONTRACT_ID, SUPPLIER_ID, PENALTY_CLAUSE_TEXT, PENALTY_PCT, SLA_DAYS) VALUES
('CTR-001', 'SUP-T1-01', 'Supplier agrees to pay a 5% delay penalty on total order value for shipments delayed beyond 3 days.', 5.00, 3);

INSERT INTO SHIPMENT (SHIPMENT_ID, ORIGIN_ID, DESTINATION_ID, LEG_TYPE, PART_ID, ORDER_ID, QTY_SHIPPED, DISPATCH_DATE, EXPECTED_DATE, STATUS) VALUES
('SHP-001', 'SUP-T1-01', 'PLANT-01', 'INBOUND', 'PART-101', 'ORD-5501', 5000, CURRENT_DATE() - 5, CURRENT_DATE() - 1, 'DELAYED'),
('SHP-003', 'SUP-T2-01', 'PLANT-01', 'INBOUND', 'PART-201', 'ORD-5501', 1000, CURRENT_DATE() - 10, CURRENT_DATE() - 2, 'DELAYED');
