USE DATABASE SCM;
USE SCHEMA ONT;

DROP SEMANTIC VIEW IF EXISTS SV_SUPPLY_CHAIN;

CREATE OR REPLACE VIEW SV_SUPPLY_CHAIN AS
SELECT
    sr.ROOT_SUPPLIER_ID,
    sr.IMPACTED_SUPPLIER_ID,
    sup.SUPPLIER_NAME       AS ROOT_SUPPLIER_NAME,
    sup.REGION              AS SUPPLIER_REGION,
    p.PART_ID,
    p.PART_NAME,
    pl.PLANT_ID,
    pl.PLANT_NAME,
    o.ORDER_ID,
    o.CUSTOMER_ID,
    sh.SHIPMENT_ID,
    sh.STATUS               AS SHIPMENT_STATUS,
    c.CONTRACT_ID,
    sr.TIER_DEPTH,
    sr.PATH_CONFIDENCE,
    sr.DAYS_TO_IMPACT,
    c.PENALTY_PCT,
    o.QTY_ORDERED,
    o.QTY_FULFILLED,
    ROUND(
        (1.0 + (sr.TIER_DEPTH * 0.3)) 
        * (COALESCE(c.PENALTY_PCT, 5.0) / 100.0) 
        * sr.PATH_CONFIDENCE 
        * 100, 
        2
    ) AS ROW_RISK_SCORE,
    IFF(sh.ACTUAL_DATE <= sh.EXPECTED_DATE, 1, 0) AS IS_ON_TIME
FROM SCM.ONT.V_SUPPLY_RISK sr
LEFT JOIN SCM.RAW.SUPPLIER sup ON sup.SUPPLIER_ID = sr.ROOT_SUPPLIER_ID
LEFT JOIN SCM.RAW.PART p        ON p.PART_ID = sr.PART_ID
LEFT JOIN SCM.RAW.PLANT pl      ON pl.PLANT_ID = sr.PLANT_ID
LEFT JOIN SCM.RAW.ORDER_ o      ON o.ORDER_ID = sr.ORDER_ID
LEFT JOIN SCM.RAW.SHIPMENT sh   ON sh.SHIPMENT_ID = sr.SHIPMENT_ID
LEFT JOIN SCM.RAW.CONTRACT c    ON c.CONTRACT_ID = sr.CONTRACT_ID;
