USE DATABASE SCM;
USE SCHEMA ONT;

-- 1. Create table for semantic search
CREATE OR REPLACE TABLE CONTRACT_SEARCH_BASE AS
SELECT 
    CONTRACT_ID,
    SUPPLIER_ID,
    PENALTY_CLAUSE_TEXT,
    PENALTY_PCT,
    SLA_DAYS
FROM SCM.RAW.CONTRACT;

-- 2. Deploy Native Cortex Search Service on Penalty Clauses
CREATE OR REPLACE CORTEX SEARCH SERVICE CORTEX_CONTRACT_SEARCH_SVC
  ON PENALTY_CLAUSE_TEXT
  ATTRIBUTES SUPPLIER_ID, PENALTY_PCT
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  AS (
    SELECT 
        CONTRACT_ID,
        SUPPLIER_ID,
        PENALTY_CLAUSE_TEXT,
        PENALTY_PCT,
        SLA_DAYS
    FROM CONTRACT_SEARCH_BASE
  );
