USE DATABASE SCM;
USE SCHEMA ONT;

-- Fallback text-matching view for legal contract clauses
CREATE OR REPLACE VIEW V_CONTRACT_CLAUSE_SEARCH AS
SELECT 
    CONTRACT_ID,
    SUPPLIER_ID,
    PENALTY_CLAUSE_TEXT,
    PENALTY_PCT,
    SLA_DAYS
FROM SCM.RAW.CONTRACT;
